spring.application.name=backend

#Database
spring.datasource.url = jdbc:postgresql://localhost:5432/diplomski_auth
spring.datasource.username=postgres
spring.datasource.password=root

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


springdoc.swagger-ui.persist-authorization=true

# JWT
jwt.secret=diplomski-super-secret-key-koji-mora-biti-dovoljno-dugacak-za-hs256
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Server
server.port=8080