spring.application.name=backend

#Database
spring.datasource.url = jdbc:postgresql://localhost:5432/diplomski_auth
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:root}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


springdoc.swagger-ui.persist-authorization=true

# JWT
jwt.secret=${JWT_SECRET:local-development-secret-key-change-in-production-123456}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Server
server.port=8080
